#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cat="bat" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	cls="clear" \
	mkd="mkdir -pv" \
  open="xdg-open" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	calcurse="calcurse -D ~/.config/calcurse"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	la="exa --git -la" \
	ll="exa --git -l" \
	ka="killall" \
	abook="abook -C ${XDG_CONFIG_HOME:-$HOME/.config}/abook/abookrc --datafile ${XDG_CONFIG_HOME:-$HOME/.config}/abook/addressbook" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	xi="sudo xbps-install -S" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Git alias
alias g="git" \
	gd="git diff" \
	gs="git status" \
	ga="git add" \
	gc="git commit -m" \
	gr="git reset" \
	gl="git log" \
	gp="git push" \
	gpom="git push origin master"

# elixir / mix / iex / phoenix aliases
alias \
	i='iex' \
	ips='iex -S mix phx.server' \
	ism='iex -S mix' \
	m='mix' \
	mab='mix archive.build' \
	mai='mix archive.install' \
	mat='mix app.tree' \
	mc='mix compile' \
	mcf='mix compile --force' \
	mcv='mix compile --verbose' \
	mcl='mix clean' \
	mca='mix do clean, deps.clean --all' \
	mco='mix coveralls' \
	mcoh='mix coveralls.html' \
	mdoc='mix docs' \
	mdl='mix dialyzer' \
	mdlp='mix dialyzer --plt' \
	mcr='mix credo' \
	mcrs='mix credo --strict' \
	mcx='mix compile.xref' \
	mdc='mix deps.compile' \
	mdg='mix deps.get' \
	mdgc='mix do deps.get, deps.compile' \
	mdu='mix deps.update' \
	mdt='mix deps.tree' \
	mdua='mix deps.update --all' \
	mdun='mix deps.unlock' \
	mduu='mix deps.unlock --unused' \
	meb='mix escript.build' \
	mec='mix ecto.create' \
	mecm='mix do ecto.create, ecto.migrate' \
	med='mix ecto.drop' \
	mem='mix ecto.migrate' \
	megm='mix ecto.gen.migration' \
	merb='mix ecto.rollback' \
	mers='mix ecto.reset' \
	mes='mix ecto.setup' \
	mge='mix gettext.extract' \
	mgem='mix gettext.extract --merge' \
	mgm='mix gettext.merge priv/gettext' \
	mho='mix hex.outdated' \
	mlh='mix local.hex' \
	mn='mix new' \
	mns='mix new --sup' \
	mpd='mix phx.digest' \
	mpgc='mix phx.gen.channel' \
	mpgco='mix phx.gen.context' \
	mpgh='mix phx.gen.html' \
	mpgj='mix phx.gen.json' \
	mpgl='mix phx.gen.live' \
	mpgm='mix phx.gen.model' \
	mpgs='mix phx.gen.secret' \
	mpn='mix phx.new' \
	mpr='mix phx.routes' \
	mps='mix phx.server' \
	mr='mix run' \
	mrnh='mix run --no-halt' \
	mrl='mix release' \
	msn='mix scenic.new' \
	msne='mix scenic.new.example' \
	msnn='mix scenic.new.nerves' \
	msr='mix scenic.run' \
	mt='mix test' \
	mtc='mix test --cover' \
	mtf='mix test --failed' \
	mtmf='mix test --max-failures' \
	mts='mix test --stale' \
	mtw='mix test.watch' \
	mx='mix xref' \
	mf='mix format'

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	alsamixer="alsamixer; kill -44 $(pidof dwmblocks)" \
	wttr="curl wttr.in" \
	pbcopy="xclip -i" \
	pbpaste="xclip -o" \
	pwdcopy="pwd | xclip -i" \
	pwdpaste='cd `xclip -o`' \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
